title: The Scala Programming Language

scalaversion: "2.12.1"

baseurl: ""
markdown: kramdown
exclude:
  - bundle-vendor/
  - blog/README.md
  - training/README.md
  - README.md
  - news/README.md
  - events/README.md
  - Gemfile
  - Gemfile.lock
future: true

# Custom collections
collections:
  scala_items:
    output: false
  online_courses:
    output: false
  trainings:
    output: false
  events:
    output: false