title: The Scala Programming Language

scalaversion: "2.10.2"
devscalaversion: "2.11.0-M4"
scala_maindownload_unix: "/files/archive/scala-2.10.2.tgz"
scala_maindownload_windows: "/files/archive/scala-2.10.2.msi"
baseurl: ""
